apiVersion: charity-project.eu/v1
kind: Component
metadata:
  name: nginx-component
spec:
  application: my-application
  image: nginx:latest
  # replicas: 1
  expose:
    - is-public: false
      is-peered: true
      is-exposing-metrics: false
      containerPort: 80
      clusterPort: 80
